### ISSUE TITLE
BufferedRWPair might have a problem?

### ISSUE THREAD

**Issue by krismaz** [krismaz/BrewLinker#17]
Traceback (most recent call last):
  File "SerialCom.py", line 120, in <module>
    setup_serial(settings['COM'])
  File "SerialCom.py", line 68, in setup_serial
    sio = io.TextIOWrapper(io.BufferedRWPair(ser, ser, buffer_size=1),
TypeError: BufferedRWPair does not take keyword arguments

**Comment by krismaz** [comment]
Nope, just python2.7
